#!/usr/bin/env python3
"""
SWARM Heat Map Visualizer
Reads heat_map.csv generated by mission_control_node and produces a visual map.

Usage:
    python3 visualize_heat_map.py                        # reads heat_map.csv in current dir
    python3 visualize_heat_map.py path/to/heat_map.csv  # reads specific file
"""

import sys
import csv
import os
import math

# ── Try to import matplotlib, fall back to ASCII if not available ─────────────
try:
    import matplotlib.pyplot as plt
    import matplotlib.colors as mcolors
    import numpy as np
    HAS_MATPLOTLIB = True
except ImportError:
    HAS_MATPLOTLIB = False
    print("matplotlib not found — falling back to ASCII map")
    print("Install with: pip3 install matplotlib numpy\n")


def load_heat_map(filepath):
    """Load heat map CSV into a dict of {(grid_x, grid_y): temp}"""
    data = {}
    metadata = {}
    grid_size = 100
    cell_size = 1.0

    with open(filepath, 'r') as f:
        reader = csv.reader(f)
        for row in reader:
            if not row:
                continue

            # Parse metadata from comments
            if row[0].startswith('#'):
                line = row[0]
                if 'Grid size:' in line:
                    parts = line.split(':')[1].strip().split('x')
                    grid_size = int(parts[0])
                elif 'Cell size:' in line:
                    cell_size = float(line.split(':')[1].strip().replace('m', ''))
                continue

            # Parse data rows: grid_x, grid_y, real_x, real_y, temperature
            if len(row) >= 5:
                try:
                    gx = int(row[0])
                    gy = int(row[1])
                    rx = float(row[2])
                    ry = float(row[3])
                    temp = float(row[4])
                    data[(gx, gy)] = {'temp': temp, 'real_x': rx, 'real_y': ry}
                except ValueError:
                    continue

    metadata['grid_size'] = grid_size
    metadata['cell_size'] = cell_size
    return data, metadata


def get_stats(data):
    """Compute basic stats from heat map data"""
    if not data:
        return {}
    
    temps = [v['temp'] for v in data.values()]
    hottest = max(data.items(), key=lambda x: x[1]['temp'])
    
    return {
        'min_temp': min(temps),
        'max_temp': max(temps),
        'avg_temp': sum(temps) / len(temps),
        'cells_visited': len(temps),
        'hottest_pos': (hottest[1]['real_x'], hottest[1]['real_y']),
        'hottest_temp': hottest[1]['temp'],
    }


def visualize_matplotlib(data, metadata, output_path):
    """Generate a proper heat map image using matplotlib"""
    grid_size = metadata['grid_size']
    cell_size = metadata['cell_size']

    # Build 2D grid — NaN for unvisited cells
    grid = np.full((grid_size, grid_size), np.nan)
    for (gx, gy), val in data.items():
        if 0 <= gx < grid_size and 0 <= gy < grid_size:
            grid[gy][gx] = val['temp']  # note: y row, x col

    # Stats
    stats = get_stats(data)

    # ── Figure setup ──────────────────────────────────────────────────────────
    fig, axes = plt.subplots(1, 2, figsize=(16, 7))
    fig.patch.set_facecolor('#0d0d0d')
    fig.suptitle('SWARM — Thermal Survey Heat Map', 
                 fontsize=18, fontweight='bold', color='white', y=0.98)

    # ── Main heat map ─────────────────────────────────────────────────────────
    ax = axes[0]
    ax.set_facecolor('#1a1a1a')

    # Custom colormap: dark blue (cool) → orange → red (hot)
    colors_list = ['#0a0a2e', '#1a237e', '#0d47a1', '#00838f', 
                   '#2e7d32', '#f9a825', '#e65100', '#b71c1c', '#ffffff']
    cmap = mcolors.LinearSegmentedColormap.from_list('swarm_thermal', colors_list)
    cmap.set_bad('#1a1a1a')  # unvisited cells = dark background

    extent = [0, grid_size * cell_size, 0, grid_size * cell_size]
    im = ax.imshow(grid, origin='lower', extent=extent,
                   cmap=cmap, vmin=20, vmax=100,
                   interpolation='bilinear', aspect='equal')

    # Fire threshold contour line (50°C boundary)
    if not np.all(np.isnan(grid)):
        try:
            contour = ax.contour(
                np.linspace(0, grid_size * cell_size, grid_size),
                np.linspace(0, grid_size * cell_size, grid_size),
                grid,
                levels=[50.0],
                colors=['#ff6b35'],
                linewidths=[2],
                linestyles=['--']
            )
            ax.clabel(contour, fmt='50°C boundary', fontsize=8, colors='#ff6b35')
        except Exception:
            pass

    # Mark hottest point
    if stats:
        hx, hy = stats['hottest_pos']
        ax.plot(hx, hy, '*', color='white', markersize=15, 
                markeredgecolor='#ff6b35', markeredgewidth=1.5,
                label=f"Hottest: {stats['hottest_temp']:.1f}°C")
        ax.legend(loc='upper right', facecolor='#1a1a1a', 
                 edgecolor='#444', labelcolor='white', fontsize=9)

    # Mark drone start
    ax.plot(0, 0, 'o', color='#00e5ff', markersize=10,
            markeredgecolor='white', markeredgewidth=1.5, label='Start')

    # Colorbar
    cbar = plt.colorbar(im, ax=ax, fraction=0.046, pad=0.04)
    cbar.set_label('Temperature (°C)', color='white', fontsize=11)
    cbar.ax.yaxis.set_tick_params(color='white')
    plt.setp(cbar.ax.yaxis.get_ticklabels(), color='white')
    cbar.ax.set_facecolor('#1a1a1a')

    # Labels
    ax.set_xlabel('X Position (m)', color='white', fontsize=11)
    ax.set_ylabel('Y Position (m)', color='white', fontsize=11)
    ax.set_title('Thermal Survey Results', color='white', fontsize=13, pad=10)
    ax.tick_params(colors='white')
    for spine in ax.spines.values():
        spine.set_edgecolor('#444')

    # ── Stats panel ───────────────────────────────────────────────────────────
    ax2 = axes[1]
    ax2.set_facecolor('#1a1a1a')
    ax2.axis('off')

    if stats:
        stat_lines = [
            ('MISSION STATS', None, '#00e5ff', 16),
            ('', None, 'white', 11),
            ('Cells Surveyed', f"{stats['cells_visited']}", '#aaaaaa', 12),
            ('Area Covered', f"{stats['cells_visited'] * cell_size:.1f} m²", '#aaaaaa', 12),
            ('', None, 'white', 11),
            ('TEMPERATURE', None, '#ff6b35', 13),
            ('Min', f"{stats['min_temp']:.1f}°C", '#aaaaaa', 12),
            ('Max', f"{stats['max_temp']:.1f}°C", '#ff4444', 12),
            ('Average', f"{stats['avg_temp']:.1f}°C", '#aaaaaa', 12),
            ('', None, 'white', 11),
            ('FIRE PERIMETER', None, '#ff6b35', 13),
            ('Threshold', '50.0°C', '#aaaaaa', 12),
            ('Hottest Point', f"({stats['hottest_pos'][0]:.1f}m, {stats['hottest_pos'][1]:.1f}m)", '#aaaaaa', 12),
            ('Peak Temp', f"{stats['hottest_temp']:.1f}°C", '#ff4444', 12),
        ]

        y_pos = 0.95
        for label, value, color, size in stat_lines:
            if value is None:
                ax2.text(0.05, y_pos, label, transform=ax2.transAxes,
                        color=color, fontsize=size, fontweight='bold')
            else:
                ax2.text(0.05, y_pos, label, transform=ax2.transAxes,
                        color='#888888', fontsize=size)
                ax2.text(0.65, y_pos, value, transform=ax2.transAxes,
                        color=color, fontsize=size, fontweight='bold')
            y_pos -= 0.065

    # Fire zone legend
    ax2.add_patch(plt.Rectangle((0.05, 0.08), 0.15, 0.04,
                                 color='#b71c1c', transform=ax2.transAxes))
    ax2.text(0.25, 0.09, 'Fire zone (>70°C)', transform=ax2.transAxes,
            color='white', fontsize=10)

    ax2.add_patch(plt.Rectangle((0.05, 0.03), 0.15, 0.04,
                                 color='#f9a825', transform=ax2.transAxes))
    ax2.text(0.25, 0.04, 'Boundary zone (50-70°C)', transform=ax2.transAxes,
            color='white', fontsize=10)

    plt.tight_layout(rect=[0, 0, 1, 0.96])
    plt.savefig(output_path, dpi=150, bbox_inches='tight',
                facecolor=fig.get_facecolor())
    print(f"Heat map saved to: {output_path}")
    plt.show()


def visualize_ascii(data, metadata):
    """ASCII fallback visualization when matplotlib is not available"""
    if not data:
        print("No data to visualize.")
        return

    grid_size = metadata['grid_size']
    stats = get_stats(data)

    # Find bounds of visited area
    if not data:
        return

    min_x = min(k[0] for k in data.keys())
    max_x = max(k[0] for k in data.keys())
    min_y = min(k[1] for k in data.keys())
    max_y = max(k[1] for k in data.keys())

    # Scale down for terminal display
    display_size = 40
    x_range = max(max_x - min_x, 1)
    y_range = max(max_y - min_y, 1)

    print("\n" + "="*60)
    print("  SWARM THERMAL HEAT MAP")
    print("="*60)

    # Build display grid
    display = [['·'] * display_size for _ in range(display_size // 2)]

    for (gx, gy), val in data.items():
        temp = val['temp']
        dx = int((gx - min_x) / x_range * (display_size - 1))
        dy = int((gy - min_y) / y_range * (display_size // 2 - 1))
        dy = display_size // 2 - 1 - dy  # flip y

        if 0 <= dx < display_size and 0 <= dy < display_size // 2:
            if temp >= 70:
                display[dy][dx] = '#'   # fire zone
            elif temp >= 50:
                display[dy][dx] = '*'   # boundary zone
            elif temp >= 35:
                display[dy][dx] = '+'   # warm zone
            else:
                display[dy][dx] = '.'   # cool zone

    # Print grid
    for row in display:
        print('  ' + ''.join(row))

    print("\nLegend:")
    print("  # = Fire zone     (>70°C)")
    print("  * = Boundary zone (50-70°C)")
    print("  + = Warm zone     (35-50°C)")
    print("  . = Cool zone     (<35°C)")
    print("  · = Not surveyed")

    if stats:
        print(f"\nStats:")
        print(f"  Cells surveyed : {stats['cells_visited']}")
        print(f"  Temp range     : {stats['min_temp']:.1f}°C — {stats['max_temp']:.1f}°C")
        print(f"  Average temp   : {stats['avg_temp']:.1f}°C")
        print(f"  Hottest point  : ({stats['hottest_pos'][0]:.1f}m, {stats['hottest_pos'][1]:.1f}m)")
        print(f"  Peak temp      : {stats['hottest_temp']:.1f}°C")
    print("="*60 + "\n")


def main():
    # Determine input file path
    if len(sys.argv) > 1:
        filepath = sys.argv[1]
    else:
        filepath = 'heat_map.csv'

    if not os.path.exists(filepath):
        print(f"Error: {filepath} not found.")
        print("Make sure the mission has completed and heat_map.csv was saved.")
        print("Usage: python3 visualize_heat_map.py [path/to/heat_map.csv]")
        sys.exit(1)

    print(f"Loading heat map from: {filepath}")
    data, metadata = load_heat_map(filepath)

    if not data:
        print("No heat map data found in file.")
        sys.exit(1)

    print(f"Loaded {len(data)} data points.")

    if HAS_MATPLOTLIB:
        output_path = filepath.replace('.csv', '.png')
        visualize_matplotlib(data, metadata, output_path)
    else:
        visualize_ascii(data, metadata)


if __name__ == '__main__':
    main()
